<p>This agreement governs your use of {$GLOBAL.website.name}.</p>
<br>
<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and any or all agreements: "Member(s)", "User", "Miner", “You” and “Your” refers to you, the person accessing this website and accepting the mining pool's terms and conditions. "The Pool", "The Mining Pool", "Ourselves", "We" and "Us", refers to the mining pool service. Any use of the above terminology or other words in the singular, plural, capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>
<p>By using any of the mining pools or registering an account on the website, you agree to be bound by the terms and conditions. If you do not agree with the terms and conditions in this agreement you may not use the mining pool.</li>
<br><br>
<ul>
  <li>The {$GLOBAL.website.name} owner/staff may modify this agreement and any policies affecting the site at any point of time. Such modification is effective immediately upon posting to the website and will be distribution via the 'site news' section on the website. Your continued use of the mining pool following any modification to this agreement shall be deemed an acceptance of all modifications.</li>
  <li>The mining pool rewards miners according to a <strong>{$GLOBAL.config.payout_system|upper}</strong> system with <strong>{$GLOBAL.fees|upper}%</strong> fee. The fee may change at any time, but notice will be given before doing so. Any fee change will be communicated through the mining pools 'site news' section.</li>
  <li>{$GLOBAL.website.name} including the owner and operators are not responsible for any loss of coins/funds which have been incorrectly sent to the wrong wallet address or sent to a wallet address where the owner (such as a exchange) is failing to release the coins/funds. Once a withdrawl of coins/funds have left {$GLOBAL.website.name} wallet the coins/funds can not be retreived.</li>
  <li>{$GLOBAL.website.name} including the owner and operators are not responsible for any loss of coins/funds which have been sent to a wallet of which you no longer have access to.</li>
  <li>The mining pool is not an electronic wallet or a bank for your coins. The mining pool including its owners/operators are not responsible for any loss of coins which are stored on the mining pool. It is the members responsibility to configure their account so that coins earned are regularly transferred to an exchange or offline wallet.</li>
  <li>In the event of a block chain fork the member ('you') will not be credited for any coins earned whilst the mining pool is connected to the forked blockchain. All transactions including credits, withdrawls, donations and transactions fees performed whilst the mining pool was connected to the forked block chain will be invalid and hold not value. {$GLOBAL.website.name} is not liable for any of these transactions whilst the mining pool is connected to the forked wallet.</li>
  <li>The up time of the mining pool and the website is not guaranteed, maintenance and downtime may be required at times. Members are responsible for configuring their miners so that they will automatically reconnect, or switch to an alternate mining pool in the case of downtime.</li>
  <li>Botnets are not welcome, accounts with a large amount of miners connecting from different IPs may be suspended without prior notice. If we are uncertain then an investigation will be opened and the member will be notified via their configured e-mail address. If we do not receive a response your account may be suspended.</li>
  <li>Multiple accounts controlled by one person may be considered as a botnet and an investigation will be opened, see above point.</li>
</ul>
<br>
<strong>Logging</strong>
<p>{$GLOBAL.website.name} use IP addresses to analyse trends, administer the site, track user actions, and gather broad demographic information for aggregate use. IP addresses are not linked to personally identifiable information. Additionally, for systems administration, detecting usage patterns and troubleshooting purposes, our web servers automatically log standard access information including browser type, access times, URL requested, and referral URL. This information is not shared with third parties and is used only within this mining pool on a need-to-know basis. Any individually identifiable information related to this data will never be used in any way different to that stated above without your explicit permission.</p>
